name: CI-CD

on: [push, pull_request]

jobs:
  php-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4]
        stability: [prefer-lowest, prefer-stable]
        experimental: [false]
        include:
          - php: 8.0
            stability: prefer-lowest
            experimental: true
          - php: 8.0
            stability: prefer-stable
            experimental: true

    continue-on-error: ${{ matrix.experimental }}

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring, bcmath

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute PHPCS
        run: composer phpcs
